# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Nick's site
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Primarily this is an experiment for a former PHP developer switching away from
  Wordpress and other CMS systems. Who knows it could lead into something else.
baseurl: "/eekdomains/" # the subpath of your site, e.g. /blog
url: "http://eekd.github.io" # the base hostname & protocol for your site
twitter_username: infosecnick
github_username:  eekd


# Build settings
markdown: kramdown
